//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTuntiLeimaus.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luokkahuone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Luokkahuone()
        {
            this.TuntiRaportti = new HashSet<TuntiRaportti>();
        }
    
        public int LuokkahuoneID { get; set; }
        public string LuokkahuoneenNimi { get; set; }
    
        public virtual Luokkahuone Luokkahuone1 { get; set; }
        public virtual Luokkahuone Luokkahuone2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuntiRaportti> TuntiRaportti { get; set; }
    }
}
