//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTuntiLeimaus.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuntiRaportti
    {
        public int IDleimaus { get; set; }
        public Nullable<System.DateTime> Sisaan { get; set; }
        public Nullable<System.DateTime> Ulos { get; set; }
        public string OppilasID { get; set; }
        public Nullable<int> LuokkahuoneID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Luokkahuone Luokkahuone { get; set; }
    }
}
